### ISSUE TITLE
Network Mode Host kills DNS on Linux host

### ISSUE THREAD

**Issue by samcro1967** [ntop/ntopng#5864]
I am able to get ntopng to work if I do not use network mode host, but then it only sees itself.  If I specify network mode host, it sees everything on the network, but DNS no longer works from any container, the Linux host, or other machines on the network.  DNS is being served by AdGuard on a Windwos host.  ntop is on a Linux VM as a docker container.  

The only way I can get DNS working again is to do a docker-compose down to remove all containers and docker compose up tp rebuild them.   I can docker exec into the containers and ping by IP fine, but by name fails unless ntopng is not in network mode host.

Anyone have any ideas?

**docker-compose**
```
 ntopng:
    hostname: ntopng
    image: ntop/ntopng:stable
    container_name: ntopng
    restart: always
    volumes:
      - "${docker}/ntopng:/var/lib/ntopng"
    network_mode: "host"
    command: --community -d /var/lib/ntopng -i eth0 --redis 192.168.1.104:6380 -w 0.0.0.0:3410
```
