### ISSUE TITLE
Tx traffic no longer being captured

### ISSUE THREAD

**Issue by matthansen0** [ntop/ntopng#7012]
**Environment**:
* OS name: Ubuntu
* OS version: 18.04
* Architecture: docker 
* ntopng version/revision: 5.4.22104.1

A few months ago, my ntopng configuration stopped capturing Tx traffic on my WAN interface. I have a port mirror setup in Hyper-V from my PFSense router to the VM I have running with ntopng in docker-compose. I don't know what build it stopped working, but I've been getting the toast message that "only Rx is detected" for a few months and you can see it in the throughput chart. 

![image](https://user-images.githubusercontent.com/23407342/205910612-31dd1800-17f8-4134-a02d-b494252d5537.png)

Nothing has changed in my docker-compose configuration and still pulls eth0 where I have both the port mirror on the router's LAN interface and eth1 where I have the WAN interface both starting. 

```
version: '3'

services:

  ntopng:
    image: ntop/ntopng
    command: --community -d /var/lib/ntopng -i eth0 -i eth1 -r 127.0.0.1:6379@0 -w 0.0.0.0:3000
    volumes:
      - ./data/ntopng:/var/lib/ntopng
    network_mode: host
    restart: unless-stopped

  redis:
    image: redis:alpine
    command: --save 900 1
    ports:
      - "6379:6379"
    volumes:
      - ./data/redis:/data
    restart: unless-stopped
```

I can confirm that when doing a tcpdump on eth1 I can see traffic in both directions on the WAN interface, for some reason though it's just not registering in ntopng anymore.

Any ideas?
