### ISSUE TITLE
Passing arguments to Docker ntopng.

### ISSUE THREAD

**Issue by huntson** [ntop/ntopng#7019]
No one answered my on Discord so I figured I'll inappropriately post this here:

I am running a ntopng docker on my Synology NAS units. For some reason, the bridge I have created for two of my interfaces does not show as an option to select in the interface list. I suppose I can use the physical aggregation function of ntopng to do the same thing…right?  Assuming that’s the case, how do I pass the appropriate argument to my docker image?

**Comment by cardigliano** [comment]
you can aggregate two interfaces with -i eth1,eth2 if you are using pf_ring as capture driver

**Comment by huntson** [comment]
This I know.  I do not know how to pass that argument to the docker at boot however.

**Comment by huntson** [comment]
Bump

**Comment by davquar** [comment]
@huntson you can specify a `command`. If you use compose, it can be something like:

```yml
# ...

app:
    container_name: ntopng
    image: ntop/ntopng
    command:
      - "/ntopng.conf"

# ...
```

Which will be expanded as `ntopng ntopng.conf` . In the file `ntopng.conf` ([docs](https://www.ntop.org/guides/ntopng/cli_options/cli_options_example.html)) you can write your arguments, like:

```
-i=/pcap/eth0
--community
# ...
```

An alternative can be directly writing the arguments instead of passing a configuration file, e.g.:

```yml
# ...

app:
    container_name: ntopng
    image: ntop/ntopng
    command:
      - "--your"
      - "--arguments"

# ...
```

Which will be expanded as `ntopng --your --arguments`.
