### ISSUE TITLE
Issue with timezone and docker:stable

### ISSUE THREAD

**Issue by earendilfr** [ntop/ntopng#7559]
**Environment**:
* OS name: docker:stable
* Architecture: amd64
* ntopng version/revision: 5.6.230531 rev.20531 

**What happened**:

I try to start the docker with the localtime correctly configured.
But, anytime, he use the UTC and not my localtime file indicated in the compose file
```yaml
  ntopng:
    container_name: ntopng
    image: 'docker.io/ntop/ntopng:stable'
    restart: always
    depends_on:
      - clickhouse
      - redis
      - nprobe
      - influxdb
    volumes:
      - "/usr/share/zoneinfo:/usr/share/zoneinfo:ro"
      - "/etc/localtime:/etc/localtime:ro"
      - "/opt/ntopng/ntopng.license:/etc/ntopng.license:ro"
      - "/opt/ntopng/ntopng/config:/etc/ntopng:rw"
      - "/opt/ntopng/ntopng/data:/var/lib/ntopng:rw"
    environment:
      - NTOP_CONFIG="/etc/ntopng/ntopng.conf"
      - TZ="Europe/Zurich"
    network_mode: "host"
    command:
      - "/etc/ntopng/ntopng.conf"
```

**How did you reproduce it?**

Modify the compose file and restart the compose with command `docker compose up -d`

**Debug Information**:

With this configuration, I have that on the shell:
```
dadmrossetam:ntopng/ $ sudo docker exec -ti ntopng /bin/sh
# ls -al /etc/localtime
lrwxrwxrwx 1 root root 23 May 31 15:35 /etc/localtime -> /usr/share/zoneinfo/UTC
#
```
