### ISSUE TITLE
Make user authentication configurable via config files

### ISSUE THREAD

**Issue by 2tefan** [ntop/ntopng#8714]
Hi! As far as I can see, there is no way to configure user authentication via config files. Could you please add support for that?

**What would you like to add or change?**:
Allow ntopng to read in a file with a configuration for user authentication, e.g. LDAPS. So basically we have a file that specifies the same things, as can be done interactively via the GUI, so for example: 
```
userAuthentication:
  LDAP:
    accountType: Posix
    serverAddress: ldaps://10.0.0.1:636
    bindDN: [...]
```

**Why do you and others need this?**:
We would like to automatically provision ntopng instances with no user input. Also, we would prefer, if we could just specify a config file instead of talking to an API :) Thank you for your time!
