### ISSUE TITLE
ntopng edge: web interface not reachable when using  dedicated management interface

### ISSUE THREAD

**Issue by sciolto** [ntop/ntopng#8924]
**Environment**:
* OS name: Ubuntu 
* OS version: 20.04 
* Architecture:  amd64
* ntopng version/revision: ntopng edge 6.2.250117

**What happened**:
We tried to setup a dedicated NIC for management, in a separate netplan configuration file `10-mgmt.yaml`: 

```
network:
  version: 2
  ethernets:
    eno8403:
      addresses: [192.168.47.47/24]
```
The Box is reachable via SSH through this address, but the Web interface is not.

Port 443 is only binded to the LAN interface of the bridge and to the backup / default address 192.168.160.10. 

**How did you reproduce it?**

See above
