### ISSUE TITLE
Suricata log not ingested as a flow

### ISSUE THREAD

**Issue by bolemo** [ntop/ntopng#8988]
Hello,

I have two machines: A and B.
A is running Suricata for years, and for now, I was using Filebeat to export the eve.json log to ELK on a docker container in machine B. It is working fine, but I find this a little heavy.
I've heard of ntopng integrating with Suricata, and decided to give it a shot.

I want to use Suricata as a sensor, meaning I want ntopng to get traffic and events strictly from the suricata output, not as a companion to a physical interface.

Extract of my suricata.yaml:
```
outputs:
(…)
   - eve-log:
       enabled: yes
       filetype: regular
       filename: eve.json
(…)
       types:
         - netflow
```

**I know that I am not using syslog**, but see further: I do export rfc5424 data to ntopng using netcat (and a little python script to convert to rfc5424).

I started a docker container with ntopng in machine B:
```
services:
  ntopng:
    image: ntop/ntopng:latest
    container_name: ntopng
    environment:
      - TZ=Europe/Paris
    ports:
      - 5140:5140
      - 3000:3000
    restart: unless-stopped
    volumes:
      - redis_data:/var/lib/redis
    command: ['--community', '--interface', 'syslog://*:5140', '--disable-login']

volumes:
  redis_data:
```

Then, on machine A, I am simulating the export of a syslog this way:
`A# tail -f eve.json | python convert_to_rfc5424.py | nc -v -t IP_OF_B 5140`
I don't want to change my logging system on this machine just for that, so simulation is the way to go for me.
_I wish I could export directly the eve.json output to ntopng._

I have tested the connection between A and B by running:
`A# tail -f eve.json | python convert_to_rfc5424.py | nc -v -t IP_OF_B 5141`
And on machine B:
`B# socat TCP-LISTEN:5141,fork -`
And I do receive the log:
```
(…)
<34>1 2025-02-24T14:40:12.719154+0100 suricata suricata - - {'timestamp': '2025-02-24T14:40:12.719154+0100', 'flow_id': 1859408303162749, 'in_iface': 'dummy0', 'event_type': 'netflow', 'src_ip': 'aaaa:bbbb:cccc:0000:0000:0000:0000:0001', 'src_port': 60584, 'dest_ip': 'dddd:eeee:ffff:0000:0000:0000:0000:0000', 'dest_port': 853, 'proto': 'TCP', 'app_proto': 'tls', 'netflow': {'pkts': 1317, 'bytes': 202413, 'start': '2025-02-24T14:37:10.629535+0100', 'end': '2025-02-24T14:39:10.678154+0100', 'age': 120, 'min_ttl': 64, 'max_ttl': 64}, 'tcp': {'tcp_flags': '1a', 'syn': True, 'psh': True, 'ack': True}, 'community_id': '1:Q09sHCTCwazFLETJSRWo1RM6QQ8='}
<34>1 2025-02-24T14:40:12.719227+0100 suricata suricata - - {'timestamp': '2025-02-24T14:40:12.719227+0100', 'flow_id': 1859408303162749, 'in_iface': 'dummy0', 'event_type': 'netflow', 'src_ip': 'dddd:eeee:ffff:0000:0000:0000:0000:0000', 'src_port': 853, 'dest_ip': 'aaaa:bbbb:cccc:0000:0000:0000:0000:0001', 'dest_port': 60584, 'proto': 'TCP', 'app_proto': 'tls', 'netflow': {'pkts': 1144, 'bytes': 310954, 'start': '2025-02-24T14:37:10.629535+0100', 'end': '2025-02-24T14:39:10.678154+0100', 'age': 120, 'min_ttl': 50, 'max_ttl': 245}, 'tcp': {'tcp_flags': '1f', 'syn': True, 'fin': True, 'rst': True, 'psh': True, 'ack': True}, 'community_id': '1:Q09sHCTCwazFLETJSRWo1RM6QQ8='}
(…)
```

The ntopng log shows it receives the syslog:
```
24/Feb/2025 14:05:40 [startup.lua:127] Initializing device polices...
24/Feb/2025 14:05:40 [startup.lua:143] Initializing alerts...
24/Feb/2025 14:05:40 [startup.lua:152] Initializing timeseries...
24/Feb/2025 14:05:40 [startup.lua:253] Completed startup.lua
24/Feb/2025 14:05:40 [NetworkInterface.cpp:3820] Started packet polling on interface 'syslog://*:5140' [id: 0]...
24/Feb/2025 14:05:41 [SyslogCollectorInterface.cpp:423] Collecting events on syslog://*:5140
24/Feb/2025 14:11:01 [SyslogCollectorInterface.cpp:252] Incoming connection from 172.25.0.1:44204
```

And on the ntopng GUI, on the interface panel, I do see the Collected Logs counter increase.

However, ntopng does not read any traffic from the log.

<img width="1733" alt="Image" src="https://github.com/user-attachments/assets/0252839c-09b4-463d-acdc-b6f0defc6e10" />

Any idea on why? It seems that ntopng is not using the received syslog to import flow/traffic information.
