### ISSUE TITLE
Preferences do not persist when re-deploying docker container

### ISSUE THREAD

**Issue by begunfx** [ntop/ntopng#9282]
**Environment**:
* OS name: Docker
* OS version: 24.0.2
* Architecture: N/A
* Running docker on Synology (DSM 7.2.2-72806 Update 3 )
* ntopng version/revision: [e.g. 5.1.211223]

**What happened**:
Anytime I try to re-deploy the docker container all my preferences get lost - including login credentials - I have to use admin/admin again.

Also, nightly backups don't seem to be run.

Here's a copy of my compose file:
```
services:
  ntopng:
    hostname: ntopng
    image: ntop/ntopng:latest
    container_name: ntopng
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    mem_limit: 4g
    cpu_shares: 768
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - /volume1/docker/ntopng:/var/lib/ntopng:rw
    network_mode: host
    command: --community -i bond0 -i bond1 --local-networks "192.168.2.0/24"
```

**How did you reproduce it?**
Simple - deplaoy the container, update credentials, make some other preference changes such as email notification, and recipient.  Setup DHCP ranges etc.  Then try to re-deploy the container.  This has happened when there is a new version available and the container gets updated via watchtower but I suspect it will still happen if you manually re-deploy.

**Debug Information**:

**Comment by cardigliano** [comment]
@begunfx ntopng keeps preferences in redis, this means you either configure redis to be persistent (e.g. map a volume where redis stores the db) or you deploy a separate container for redis.

**Comment by begunfx** [comment]
Thanks for the response @cardigliano.  I tried adding a volume specifically for redis data (I used gemini to help with the path).
Still no luck.  Data is not persisting.

This my new compose file.
```
services:
  ntopng:
    hostname: ntopng
    image: ntop/ntopng:latest
    container_name: ntopng
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    mem_limit: 4g
    cpu_shares: 768
    environment:
       TZ: America/Los_Angeles
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - /volume1/docker/ntopng:/var/lib/ntopng:rw
      - /volume1/docker/ntopng/redis_data:/var/lib/redis:rw
    network_mode: host # This is correct for seeing host interfaces
    # IMPORTANT CHANGE HERE: Specify both interfaces using separate '-i' flags
    command: --community -i bond0 -i bond1 --local-networks "192.168.2.0/24"
```

**Comment by begunfx** [comment]
So after a failed attempt to get redis to persist via just a volume mount, with Gemini's help I built a new compose file that uses redis in a separate container.  I believe this is working now.  Feel free to validate this (I cleaned up some of the extra notes Gemini had added for context):

```
services:
  # --- Redis Service ---
  redis:
    image: redis:7-alpine
    container_name: ntopng-redis
    restart: unless-stopped
    command: redis-server --appendonly yes --appendfsync everysec --dir /data
    volumes:
      - /volume1/docker/ntopng/redis_data:/data:rw
    ports:
      - "6379:6379"
    networks:
      - ntopng_net

  # --- ntopng Service ---
  ntopng:
    hostname: ntopng
    image: ntop/ntopng:latest
    container_name: ntopng
    healthcheck:
      test: timeout 10s bash -c ':> /dev/tcp/127.0.0.1/3000' || exit 1
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    mem_limit: 4g
    cpu_shares: 768
    environment:
       PUID: 1026
       PGID: 100
       TZ: America/Los_Angeles
    security_opt:
      - no-new-privileges:true
    restart: unless-stopped
    volumes:
      - /volume1/docker/ntopng:/var/lib/ntopng:rw
    network_mode: host
    command: --community -i bond0 -i bond1 --local-networks "192.168.2.0/24" --redis 127.0.0.1:6379
    depends_on:
      - redis

networks:
  ntopng_net:
    driver: bridge
```
